.github/workflows/pip.yml
scpdt/_run.py
scpdt/_util.py

Temporarily switch the backend to Agg. 
This is ported straight from refguide-check. The switch currently lives in `testmod`, which seems to make sense: DTRunner does not need to worry about any of these.
closes gh-6
Also try running the doctest on a private scipy submodule (which is a hack, yes).

Suppress matplotlib figuires

---

scpdt/_run.py
scpdt/_tests/test_testmod.py

cross-ref gh-14
Emitting dots or F does not seem to play very nice with the doctest structure --- it requires to have two separate streams, one to capture the doctest reports, and the other for for '...F....'. It feels like it's going to evolve into an inferior homemade pytest clone, so pass on it for now and only use three levels: 0 is failures only; 1 is emit object names just before doctesting; 2 is full, emit all examples.
Let's see how this fares on larger workloads (scipy then numpy).
Note that it's a job for a testmod-like wrapper, because DTRunner's `report_*` hooks work per-example, not per-docstring.

ENH: add a three-state verbosity level : 0, 1, 2 in testmod

---

scpdt/_run.py
scpdt/_tests/test_finder.py
scpdt/_util.py

`finder.find(...)` tries to guess an object name if not provided. The guess is basically `obj.__name__`. This works fine most of the time, but fails for e.g. module-level constants, as those do  *not* have a `__name__` attribute.
Failures are observed in  `scipy.constants`, `scipy.stats` and `scipy.odr`.
Thus return the names explicitly.

BUG: handle missing __name__s in finder(..., strategy='public')

---

scpdt/_checker.py
scpdt/_run.py
scpdt/_tests/failure_cases_2.py
scpdt/_tests/test_testmod.py
scpdt/_util.py

These patches are ported from doctest_scip_api branch, which runs `testmod` on scipy submodules.
1. Add a user-provided context manager hook to DTConfig, add a sample implementation (a noop stub, basically)
2. Suppress excessive name errors after an unexpected exception.
Details are in the commit messages. <s>Maybe</s> 2. should grow an entry in DTConfig. --- done

Allow user context managers, suppress spurious NameErrors

---

.github/workflows/pip.yml
README.md
scpdt/__init__.py
scpdt/__main__.py
scpdt/_frontend.py

Can do `$ python -m scpdt pythonsource.py`' to mimic `$ python -m doctest`

ENH: add a basic CLI for *.py files

---

scpdt/__init__.py
scpdt/_frontend.py
scpdt/_impl.py
scpdt/_tests/__init__.py
scpdt/_tests/test_finder.py
scpdt/_tests/test_parser.py
scpdt/_tests/test_runner.py
scpdt/_tests/test_testfile.py
scpdt/_tests/test_testmod.py
scpdt/_util.py

Add a basic `testfile` to accompany `testmod`. Since testfile does not invoke DTFinder, move the stopword list to a DTParser.
TODO for DTFinder / DTParser:
... and then can actually work on `testfile`.

add DTParser and a stub testfile

---

scpdt/_impl.py
scpdt/_tests/module_cases.py

When run with warnings->errors, these trigger a failure in e.g. `scipy.sparse.linalg.lobpcg`, because:
- the abbreviation of `np.diag(np.arange(1000))` contains a `...`
- which is interpreted as an Ellipsis, hence `a_want/a_got` become object arrays + a PendingDeprecationWarning is emitted
- this warning turned to error triggers a test failure without   that much of a useful message.
The error reporting might need to be improved indeed, but that's separate. Currently, filtering out these errors is a correct thing to do as long as DTChecker does `w_want = eval(want)` etc.

ENH: filter PendingDeprecationWarnings in DTChecker want->a_want etc

---

scpdt/_frontend.py
scpdt/_impl.py
scpdt/_tests/local_file_cases.py
scpdt/_tests/test_testmod.py
scpdt/_util.py

Doctests are run in a tempdir, so if a doctest tries to open a local file, the file is not found---unless copied manually.
Thus add an entry to DTConfig, `config.local_resources`, which is a dict where keys are `test.name`s and values
are lists of filenames to copy. The file names are relative to `test.filename`, i.e. most likely the sourcefile/module being
doctested.
closes gh-43

ENH: allow for local files

---

scpdt/_frontend.py
scpdt/_impl.py
scpdt/_tests/scipy_linalg_tutorial_clone.rst
scpdt/_util.py

Also provide a default and a current scipy version, both in _util.
closes gh-27

ENH: add rndm_state to DTConfig to make it user-configurable

---

README.md
scpdt/_impl.py
scpdt/_tests/test_skipmarkers.py

cf gh-10, there is finally a need for this, in numpy rst tutorials.
The original refguide-check implementation is a hack, the idea of adding a doctest optionflag is from the numpy version of refguide-check.
Here the implementation is to add a `# doctest: +SKIP` internally to every Example in a block.

ENH: implement the +SKIPBLOCK optionflag

---

scpdt/_frontend.py
scpdt/_impl.py
scpdt/_util.py

Controlling the rng behavior is on the user, in the user_context_mgr.
closes gh-54

ENH: remove a separate rndm_state context manager

---

.github/workflows/pip.yml
.gitignore
pyproject.toml
scpdt/impl.py
scpdt/plugin.py
scpdt/tests/failure_cases.py
scpdt/tests/module_cases.py
scpdt/tests/test_pytest_configuration.py

- implemented the `pytest_configure` hook to register `DTChecker` as a plugin thus allowing pytest to use it during doctest execution.
- overrode the [`_get_checker`]( https://github.com/pytest-dev/pytest/blob/7c30f674c58ee16f2b74ef85bb8765252764ef70/src/_pytest/doctest.py#L678) function to return the `DTChecker`.
- added test cases to assert that pytest utilizes the DTChecker which handles numpy's intricacies.
- changed the `default_namespace` attribute to {} for explicit import of `numpy` in test examples.
- explicitly imported `numpy` in all docstring test examples.
- added a CI test that performs doctests through the plugin.
Closes #72

ENH: Configure pytest to use DTChecker

---

.github/workflows/pip.yml
scpdt/plugin.py
scpdt/tests/test_pytest_configuration.py

- overrode the [`DoctestModule`](https://github.com/pytest-dev/pytest/blob/7008385253939271c7046f37f4008e1b7dcbe75c/src/_pytest/doctest.py#L497) class to use the `DTFinder` which utilizes the `DTParser` when creating a [DoctestItem](https://github.com/pytest-dev/pytest/blob/7008385253939271c7046f37f4008e1b7dcbe75c/src/_pytest/doctest.py#L252)
- overrode the [`DoctestTextfile`](https://github.com/pytest-dev/pytest/blob/7008385253939271c7046f37f4008e1b7dcbe75c/src/_pytest/doctest.py#L417) to use an instance of DTParser
-  added a test case to ensure pytest goes through the `DTParser` to filter out stopwords and pseudocode in modules.
- update the CI to include a test for the `stopwords_cases` module through the plugin.
Closes #73

ENH: Configure pytest to use DTParser & DTFinder

---

.github/workflows/pip.yml
scpdt/conftest.py
scpdt/plugin.py
scpdt/tests/conftest.py
scpdt/tests/test_pytest_configuration.py

- created a `DTConfig` object in `conftest.py` with `local_resources` specified that is passed to instances of `DTChecker`, `DTFinder` and `DTParser`
- created a `copy_local_files` function that ensures local files defined by config's `local_resources` attribute are copied to the cwd where pytest carries out its tests
- implemented the `pytest_unconfigure` hook to ensure all copied local files are deleted when testing is complete
- created a `copy_files` autouse fixture to ensure all local files are copied to the temporary directory used by `pytester` during self testing

Copy local files to current working directory

---

scpdt/conftest.py
scpdt/impl.py
scpdt/plugin.py

- plugged in the `DebugDTRunner`
- overrode its `run` function to ensure tests are run in context managers
Closes #82

Run tests in context managers

---

scpdt/conftest.py
scpdt/tests/local_file_cases.py

Since the specification of the`local_resources` attribute is particular to the plugin's doctests, I moved it to the `local_files` module.
Now projects can use the `dt_config` instance with default configurations.

FIX: Move `local_resources` specification to module

---

scpdt/impl.py
scpdt/plugin.py
scpdt/tests/local_file_cases.py
scpdt/util.py

- used scpdt's `find_doctests` to discover doctests in public objects.

ENH: Execute doctests in numpy unfuncs and compiled functions

---

scpdt/plugin.py

- Deprecation warnings are now being filtered at the point of running the deprecated function.
Closes #93

ENH: Filter deprecation warnings

---

.github/workflows/pip.yml

scipy.ndimage seems more stable than scipy.linalg?

CI: run tests with pytest < 8; test ndimage not linalg

---

.github/workflows/pip.yml
scpdt/impl.py
scpdt/plugin.py

Refactor the doctest collection stage a bit. 
The key simplifications are
- for dev installs, only run pytest on the `build-install` folder. Its contents matches the installed version, so it should be identical to `$ pytest --pyargs scipy` for an installed scipy (I think?). This obviates the need for the `PY_IGNORE_IMPORTMISMATCH=1` env var --- almost. The remaining need seems to be due to some weirdness in `scipy.signal`, which indeed has a matching `.py` and `.so` modules:
```
E   _pytest.pathlib.ImportPathMismatchError: ('scipy.signal._spectral', '/home/br/repos/scipy/scipy/build-install/lib/python3.10/site-packages/scipy/signal/_spectral.cpython-310-x86_64-linux-gnu.so', PosixPath('/home/br/repos/scipy/scipy/build-install/lib/python3.10/site-packages/scipy/signal/_spectral.py'))
``` …

Refactor `pytest_collection_modify` hook

---

scpdt/plugin.py

With this, checking scipy using the recipe from https://github.com/ev-br/scpdt/pull/107 seems to work. This obviates the need for several whitespace fixes from https://github.com/scipy/scipy/pull/19242.
(split off gh-111)

BUG: plugin: get optionflags from DTConfig

---

.github/workflows/pip.yml

closes gh-108 --- that issue was a fluke, apparently? Or one of refactorings fixed it.

CI: add a workflow with pytest == 8

---

scpdt/plugin.py

- Put back the skip of docstrings with no doctest examples: pytest does it, and there is no reason not to. If we don't skip them here, `pytest --doctest-modules` reports them as if they had `+SKIP` anyway.
- Stop filtering all DeprecationWarnings. This was a temp filter IIUC, and this is bad practice in general. Either rewrite the docstring to avoid deprecated stuff, or use a more granular filter in `dt_context.user_context_mgr`.

Skip empty doctests, stop blank filtering DeprecationWarnings

---

scpdt/plugin.py

In `plugin.py`, rename `_pytest.doctest` to `pydoctest` to clarify what comes from the stdlib and what is from pytest.
(e.g. `doctest.DoctestFinder` is from stdlib, and `pydoctest.DocTestModule` is from pytest)
closes gh-115

MAINT: clean up imports, naming in the plugin

---

scpdt/impl.py

Explicit `doctest.DocTestRunnner(self, ...)`  are from python 2 era where doctest was using old-style classes (yes indeed).

MAINT: use super() in DTRunner

---

scpdt/plugin.py
scpdt/tests/local_file_cases.py
scpdt/tests/test_pytest_configuration.py
scpdt/util.py

When ready, will fix gh-101
(edited)

BUG: run tests in a tempdir, copy needed local files

---

README.md
scpdt/plugin.py

This is a breaking change: the default collection strategy changes from  "api" to vanilla pytest.
Add a cmdline option, `--doctest-collect={None, api}`
The default is now the vanilla doctest collection, `strategy=None`. To select `strategy='api'`, use the command flag
```
$ pytest --doctest-modules --doctest-collect=api
```
When to use what. strategy='api' is meant for packages with non-trivial internal structure and where you only enfore doctests correctness for public objects.
For individual single-file modules, you probably want strategy=None.
closes gh-114
P.S. I manually checked 
- the collection log still agrees with https://github.com/ev-br/scpdt/wiki/Compare-the-coverage
- individual files are no longer skipped: `pytest --doctest-modules …

ENH: make collection strategy user configurable in the pytest layer

---

scpdt/plugin.py

- get optionflags from DTConfig
- allow pytest_extra_skips in collection
This is a minimal fix to close #130:  the following passes on scipy
```
$ python dev.py shell
$ cd scipy/doc/source/tutorials
$ pytest doc/source/tutorial/ --doctest-glob=*rst
```
Further enhancements are tracked in #132, #56.
Further UX improvements:
- why is `--doctest-glob=*rst` needed? Looks like there's an issue in https://github.com/pytest-dev/pytest/blob/8.0.2/src/_pytest/doctest.py#L138 and https://github.com/pytest-dev/pytest/blob/8.0.2/src/_pytest/doctest.py#L151 --- figure out or report upstream?
- cook up a nicer UX for `dev.py`: with refguide-check it was "skip tutorials if -s submodule, run them otherwise". Not nice.

BUG: fix testing *rst tutorials

---

scpdt/plugin.py

The `try-except-pass` stanza was bothering me every time I saw it. 
Turns out it was to filter out modules which are deprecated, meaning they emit a DeprecationWarning on an attribute access. Consider
```
In [1]: from scipy.constants import constants      # deprecated submodule constants.constants
In [2]: constants.zetta      # DeprecationWarning
<ipython-input-5-835b60441caf>:1: DeprecationWarning: Please import `zetta` from the `scipy.constants` namespace; the `scipy.constants.constants` namespace is deprecated and will be removed in SciPy 2.0.0.
constants.zetta
Out[5]: 1e+21
```
Note however that non-existent attributes still raise an AttributeError, only with a helpful error message:
```
In [3]: constants.tapas                 # non-existent attr: AttributeError w/ special error …
```

MAINT: a nicer way to detect a module is deprecated in DTModule

---

scpdt/plugin.py

With this, running
```
$ pytest --pyargs scipy --doctest-modules --ignore=/home/br/repos/scipy/scipy/build-install/lib/python3.10/site-packages/scipy/_lib --ignore=../../repos/scipy/scipy/build-install/lib/python3.10/site-packages/scipy/interpolate/_interpnd_info.py --doctest-collect=api -x ================================= test session starts ================================== platform linux -- Python 3.10.10, pytest-8.0.1, pluggy-1.3.0 rootdir: /home/br/sweethome/temp
plugins: scpdt-0.1, anyio-4.2.0, cov-4.0.0, timeout-2.1.0, hypothesis-6.84.3, xdist-3.2.1 collected 2497 items
cluster/hierarchy.py ...............................                             [  2%]
cluster/vq.py ....                                                               [  2%]
constants/__init__.py ............... …
```

BUG: more robust filter DeprecationWarnings

---

scpdt/plugin.py

MAINT: try fixing a collection error under pytest 8.1.x

---

scpdt/util.py

MPL 3.8 issues a DeprecationWarning, follow its suggestion:
scpdt/tests/test_testfile.py::test_one_scipy_tutorial
Auto-close()ing of figures upon backend switching is deprecated since 3.8 and will be removed two minor releases later.  To suppress this warning, explicitly call plt.close('all') first.
matplotlib.use('Agg')
Found while looking at gh-131

MAINT: close the figures before backend change

---

scpdt/impl.py
scpdt/plugin.py
scpdt/tests/test_pytest_configuration.py
scpdt/tests/test_runner.py

Add CheckerKlass attribute to DTConfig for the class name of the Checker, use in instantiating the Runner. Then it percolates all the way up to all sorts of frontends, both doctest and pytest layers.
DTConfig gets a bit crowded, and it becomes easy to silently ignore some keys: VanillaOutputChecker ignores atol/rtol etc. If this ever becomes a problem, can add more structure to DTConfig. 
The right thing is likely to make DTConfig hold actual objects not classes and their instantiation parameters.
That would be a larger change though, so let's get there when it gets more usage.
Until then, let's keep it simple. 
cross-ref gh-38.

ENH: make OutputChecker pluggable

---

scpdt/impl.py
scpdt/util.py

Otherwise self-tests simply hang: np.VisibleDeprecatinWarning is not found at https://github.com/ev-br/scpdt/blob/main/scpdt/impl.py#L254, so we get into the `except Exception:` branch and it all goes downhill from there.
cross-ref https://github.com/ev-br/scpdt/issues/79#issuecomment-1963747649

MAINT: Adapt to NumPy 2.0

---

scpdt/impl.py

Only retry on a masked array if it actually has masked values.
Falls out for NumPy < 2.0 handling of stats.describe: otherwise the very presence of a masked array triggers an infinite loop terminating at the recursion limit.

BUG: make handling of masked arrays more specific

---

scpdt/impl.py
scpdt/tests/module_cases.py

closes gh-150
(now that I finally RTFM, `allclose` does have an `equal_nan=True` switch).
While at it, handle complex nans and infs.

ENH: treat nans as equal

---

scipy_doctest/impl.py
scipy_doctest/tests/module_cases.py

Old-style numpy format, `[ 0 1 2 ]` was adding whitespace after the opening bracket. This was throwing off the attempt at reinserting the commas, which was trying to eval `[, 0, 1, 2, ]` instead of `[0, 1, 2]`. Thus the checker was falling back to the (whitespace-sensitive) vanilla doctest.

ENH: more robust detection of printed arrays

---

scipy_doctest/frontend.py
scipy_doctest/util.py

get_public_object calls `getattr(module, name)`. This can emit a DeprecationWarning, so do it under config.user_context_manager() so that users can filter out these warnings.

ENH: allow filtering out import errors on get_public_object

---

scipy_doctest/__init__.py

Otherwise, `import scipy_doctest` emits obscure warnings from `pytest` on reimports.

BUG: pytest register_assert_rewrites of internal modules

---

README.md
scipy_doctest/impl.py

- bring `pytest` usage to the front
- replace the list of DTConfig attributes with a link to the docstring: the duplicate listing was correct when written, and was missing several more recent additions. We probably prefer to keep a single source of truth
- actually update the `DTConfig` docstring.

Rework the readme

---

.github/workflows/pip.yml
scipy_doctest/tests/local_file_cases.py
scipy_doctest/tests/test_pytest_configuration.py

Fixes #154 where the incorrect file path was specified for the doctest, `sio`, that required a local file, `octave_a.mat`

BUG: Correct filepath for doctest requiring local resource

---

scipy_doctest/impl.py
scipy_doctest/tests/failure_cases.py
scipy_doctest/tests/test_testmod.py

This is to decide whether to require matching dtypes or rely on NumPy's lax definition of equality:
```
>>> np.float64(3) == 3
True
```
closes https://github.com/scipy/scipy_doctest/issues/172

ENH: add a strict_check flag to (optionally) check dtypes

---

.github/workflows/pip.yml
scipy_doctest/impl.py
scipy_doctest/tests/module_cases.py

NumPy 2.2 added shape= to the repr of abbreviated arrays. This is not a legal argument to `array(...)` constructor, thus the result cannot be eval-ed.
Thus, remove the `shape=...` bit, if present, from both `want` and `got`. Then try to cater for both "new" and "old" numpy outputs:
- if `shape=` is present in the output, i.e. on NumPy >= 2.2, compare both shapes and values
- if `shape=` is not present in the output, i.e. on NumPy < 2.2, only compare the values.
This way, doctests written in the numpy 2.2+ format, continue working across all numpy versions. Doctests written for the "old" format do not work on numpy 2.2+ and need a tweak to add `shapes=...`.
closes gh-175

Numpy 2.2 abbreviations

---

scipy_doctest/impl.py
scipy_doctest/tests/test_finder.py

cross-ref https://github.com/python/cpython/issues/127962, https://github.com/numpy/numpy/issues/28002
fixes gh-178

BUG: collect doctests from docstrings of data descriptors

---

README.md

Now that Lucas packaged scipy-doctest to conda-forge (thank you!), let's add version badges to README.
cc @lucascolley

DOC: add pypi/conda-forge badges to README

---

README.md

No idea what this really does, but apparently it does something. See the discussion around https://github.com/scipy/scipy_doctest/pull/179#issuecomment-2549444952

DOC: mention `--import-mode=importlib` for editable installs

---

.github/workflows/pip.yml
scipy_doctest/impl.py
scipy_doctest/tests/module_cases.py

Looks like it's no longer needed now taht we do not create object arrays for numpy array abbreviations.
While at it, tweak the CI a bit:
- enforce a run with `numpy < 2`
- stop fretting about `pytest < 8`

Stop filtering VisibleDeprecationWarning from numpy

---

.github/workflows/pip.yml
scipy_doctest/impl.py
scipy_doctest/tests/test_skipmarkers.py

This is a ~~partial~~ now hopefully complete fix for https://github.com/scipy/scipy_doctest/issues/191. See https://github.com/python/cpython/commit/4f9b706c6f5d4422a398146bfd011daedaef1851.

Adapt to changes to doctest statistic tracking internals in Python 3.13

---

pyproject.toml
scipy_doctest/tests/test_testmod.py

Was needed to blacklist scipy==1.5.1
closes gh-184

MAINT : stop upper capping scipy

---

scipy_doctest/impl.py
scipy_doctest/tests/failure_cases.py
scipy_doctest/tests/module_cases.py
scipy_doctest/tests/test_testmod.py

Previously, dict comparisons were only comparing keys and ignored the values.
closes gh-195

ENH: handle dicts

---

README.md
scipy_doctest/plugin.py

The default is True, for now.
The plan is to make it False in v2.0, so that
`$ pytest --doctest-modules
`
runs both doctests and regular tests (consistent which vanilla doctest), and then the current behavior (== only run doctests) will require
`$ pytest --doctest-modules --doctest-only-doctests=true`
cross-ref gh-198
TODO

ENH: add --doctest-only-doctests={true,false} option

---

scipy_doctest/impl.py
scipy_doctest/tests/failure_cases.py
scipy_doctest/tests/module_cases.py
scipy_doctest/tests/test_testmod.py

Previously, these cases would fall back to vanilla pytest.
The problem is two-fold:
1. `np.allclose('a', 'a')` fails with a `DTypePromotionError`;
2. Our recursive treatment of nested data structures is limited.  It fails to parse `[('a', 2), ('b', 3)]` and falls back to the
vanilla doctest.
Therefore, we handle dictionaries by checking the keys and values separately, instead of trying to convert a dict into a list of pairs.
cross-ref gh-202

ENH: make dicts with string keys use numeric comparisons

---

scipy_doctest/tests/module_cases.py

The `__all__` list is used in test_testmod.py::test_public_object_discovery The test only needs the list to be present and not empty. That said, let's make `__all__` actually correct, if only to save confusion going forward.

MAINT: fix tests/module_cases.__all__

---

.github/workflows/docs.yml
.github/workflows/pip.yml

Apparenty, this is the security recommendation to use hashes instead of versions.
[as to why: "versions/tages are mutable, hashes are not", end of quote]
Parrot the hashes themselves from SciPy main, where available.

CI: use hashes for the actions

---

.github/workflows/pip.yml
scipy_doctest/util.py

CI: test on python 3.8, too
